# Generated by Django 4.2.10 on 2026-01-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, help_text='Stripe event ID (evt_xxx)', max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, help_text='Stripe event type (e.g., checkout.session.completed)', max_length=100)),
                ('processed', models.BooleanField(db_index=True, default=False, help_text='Whether this event has been successfully processed')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the event was processed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_data', models.JSONField(blank=True, help_text='Raw event data (for debugging)', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['event_id'], name='billing_web_event_i_0dccbf_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['event_type', 'processed'], name='billing_web_event_t_e3f298_idx'),
        ),
    ]
