# Generated by Django 6.0.1 on 2026-01-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_pro',
            new_name='is_subscribed',
        ),
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
