# Generated by Django 6.0.1 on 2026-01-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_is_pro_profile_is_subscribed_profile_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='trial_end',
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
