# Generated by Django 5.2 on 2026-01-13 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_plan_remove_profile_trial_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID (cus_xxx)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe Subscription ID (sub_xxx)', max_length=255, null=True),
        ),
    ]
