# Generated by Django 4.2.10 on 2026-01-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_enhancements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at']},
        ),
    ]
